# Generated by Django 4.2.3 on 2023-12-20 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import validation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ref_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(99), django.core.validators.MaxValueValidator(999)], verbose_name='Reference Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(validators=[validation.models.validate_age], verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_type', models.CharField(choices=[('RA', 'Personal Car Plate'), ('RDF', 'Security Organs Car Plate (RDF)'), ('RNP', 'Security Organs Car Plate (RNP)'), ('GP', 'Government Managed Plate (GP)'), ('GR', 'Government Managed Plate (GR)'), ('IT', 'Government Managed Plate (IT)')], max_length=3)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=10)),
                ('participant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='validation.participant')),
            ],
        ),
    ]
